### ISSUE TITLE
Spotify card stuck in loading since HomeAssistant 2023.3

### ISSUE THREAD

**Issue by jason-glynn** [custom-cards/spotify-card#197]
spotify card stuck on "loading" message with no playlists displaying since Home Assistant 2023.3. Using v2.4 of card.

**Comment by Frowxen** [comment]
Same here! Always appear loading

**Comment by leothlon** [comment]
I have two accounts, first one (my wifes) fetches playlist perfectly.
Second account (mine) just say "Loading..." (but it does say correctly for currently playing)

i have removed and re-added both accounts multiple times, but its always the same.. wifes account works, mine does not

**Comment by jurand71** [comment]
Did you find any solution, I have exactly the same effect, It starts from 2023.3 v

Edit: the problem solved, sp_key as sp_dc changed

**Comment by tstill88** [comment]
> Did you find any solution, I have exactly the same effect, It starts from 2023.3 v
> 
> Edit: the problem solved, sp_key as sp_dc changed

What did you mean sp_key as sp_dc?

Mine is still loading and says Spotify integration needs to be installed for this to work which it as as im using the media_player.spotify_username without issues.

**Comment by jurand71** [comment]
All information you need about sp_key and sp_dc you find here: https://github.com/fondberg/spotcast

**Comment by tstill88** [comment]
> All information you need about sp_key and sp_dc you find here: https://github.com/fondberg/spotcast

Ahh perfect, didnt think to check that integration. Just had to rebuild HA and must have missed it. Thanks!

**Comment by skavan** [comment]
Did all the above.
The spotcast service works fine when run.
But still "Loading..."
Ugh! Any ideas --- anyone?

**Comment by javiges** [comment]
> Hizo todo lo anterior. El servicio spotcast funciona bien cuando se ejecuta. Pero aún "Cargando..." ¡Uf! ¿Alguna idea? ¿Alguien?

+1

**Comment by ezeklusman** [comment]
+1 Spotify Premium user here, set up sp_dc and sp_key but always get the 'Loading...' message.
Any help?

**Comment by skavan** [comment]
reauthenticate spotify with new web credentials...and grab the new keys from cookies. fixed.
I must have changed my password and forgot. Or maybe spotify updated the credentials themselved.

**Comment by Pirol62** [comment]
Hi, does anyony find a solution here. Since 2024.12.1 spotcast is working fine here. So I don't habe any issues with the keys. But the lovelace card is permanetly loading

**Comment by JOHLC** [comment]
> Hi, does anyony find a solution here. Since 2024.12.1 spotcast is working fine here. So I don't habe any issues with the keys. But the lovelace card is permanetly loading

 Mine is as well. In my web browser console, I am seeing these errors:
 
```
2services.js:31  Uncaught (in promise) TypeError: this.chromecast_devices.filter is not a function
    at Qe.getFilteredDevices (services.js:31:82)
    at Qe.generateDeviceList (services.js:31:82)
    at Qe.render (services.js:31:82)
    at Qe.update (spotify-card.js?hacstag=173955605240:186:1183)
    at Qe.performUpdate (spotify-card.js?hacstag=173955605240:148:6614)
    at Qe._enqueueUpdate (spotify-card.js?hacstag=173955605240:148:6302)
index.m.js:1  Uncaught (in promise) Error: Failed to fetch playlists: [object Object]
    at Re.fetchPlaylists (index.m.js:1:4274)
    at async entities.js:28:83
index.m.js:1  Uncaught (in promise) Error: Failed to fetch playlists: [object Object]
    at Re.fetchPlaylists (index.m.js:1:4274)
    at async entities.js:28:83
```
 
 I have completely rebuilt my config for my account, spotcast, and the card and everything is working fine except for the card.

**Comment by JOHLC** [comment]
Just realized this repo is no longer being developed and that they are talking about this issue over here: 
https://github.com/mikevanes/spotify-card-v2/issues/16
