### ISSUE TITLE
Chromecast: failed to call service spotcast/start

### ISSUE THREAD

**Issue by sdekker90** [custom-cards/spotify-card#38]
Hi,

I am unable to start a playlist on a chromecast device. The devices are listed, but when I click on any of them, I get the message "Failed to call service spotcast/start. Service not found"

![image](https://user-images.githubusercontent.com/25793879/71717022-f56de680-2e16-11ea-9c89-ce2e10d5fbbc.png)

> Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 205, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 336, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 358, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/spotify/media_player.py", line 280, in media_play
    self._player.start_playback()
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 913, in start_playback
    return self._put(self._append_device_id("me/player/play", device_id), payload=data)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 190, in _put
    return self._internal_call('PUT', url, payload, kwargs)
  File "/usr/local/lib/python3.7/site-packages/spotipy/client.py", line 126, in _internal_call
    headers=r.headers)
spotipy.client.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/me/player/play:
 Player command failed: No active device found

**Comment by sdekker90** [comment]
My spotify account was linked to a facebook account, thus the login didn't work. I converted my facebook spotify account to an email spotify account and now the login works fine.

**Comment by davidrustingha** [comment]
Hi there,

I have the same problem, whenever I click on the chromecast device, it says "Failed to call service spotcast/start. Service not found". My account is linked to a spotify Family account, could this be the reason for the error?

**Comment by gridi88** [comment]
have the same error, any news?

**Comment by fondberg** [comment]
You need to install spotcast https://github.com/fondberg/spotcast/
